FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

RUN pip install deprecated pydantic==1.10.12 numpy==1.24.3 scikit-image "https://s3-us-west-2.amazonaws.com/ray-wheels/master/4f2ec46c3adb6ba9f412f09a9732f436c4a5d0c9/ray-3.0.0.dev0-cp311-cp311-manylinux2014_x86_64.whl" gymnasium dm_tree scipy rotary_embedding_torch pymap3d pettingzoo swig wheel 'conan<2.0' matplotlib  pytest pytest-html pytest-xdist setuptools-scm cmake 

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y build-essential python3-tk git tmux 

WORKDIR /
RUN git clone https://github.com/AVSLab/basilisk.git
WORKDIR /basilisk
RUN git checkout fc71539
RUN python conanfile.py