
services:
  constsched:
    build:
      context: .
      dockerfile: Dockerfile.ray
    shm_size: '10.24gb' 
    network_mode: host
    volumes:
      - ../:/ConstSched
    working_dir: /ConstSched
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    command: tail -f /dev/null 
