
local_mode: false # I think reduces to single process, for debugging
use_gpu: true

env_runners:
  sample_timeout_s: 1000000.0
  num_env_runners: 8
  num_cpus_per_env_runner: 2

training:
  steps: 100000

training_args:
  lr: 0.00003
  gamma: 0.0
  train_batch_size: 128
  sgd_minibatch_size: 32 # Default is 128
  num_sgd_iter: 8 # Default is 30
  lambda_: 0.95
  kl_target: 0.01
  kl_coeff: 0.2
  use_kl_loss: True
  clip_param: 0.2
  grad_clip: 0.5


env:
  sim_rate: 1.0
  max_step_duration: 200.0
  time_limit: 11400 # about 2 orbits
  n_access_windows: 10
  n_sats: 10

  n_trajectory_factor: 20

  min_tasks: 100
  max_tasks: 3000

  max_sat_coordination: 3

