
local_mode: True # I think reduces to single process, for debugging

env_runners:
  sample_timeout_s: 1000000.0
  num_env_runners: 7

training:
  steps: 100000

training_args:
  lr: 0.00003
  gamma: 0.999
  train_batch_size: 250
  num_sgd_iter: 10
  lambda_: 0.95
  use_kl_loss: False
  clip_param: 0.1
  grad_clip: 0.5


env:
  sim_rate: 1.0
  max_step_duration: 180.0
  time_limit: 6000
  n_access_windows: 10
  n_sats: 50

  min_tasks: 300
  max_tasks: 3000

