
local_mode: false # I think reduces to single process, for debugging
use_gpu: true

env_runners:
  sample_timeout_s: 1000000.0
  num_env_runners: 24
  num_cpus_per_env_runner: 1

training:
  steps: 100000

training_args:
  lr: 0.00003
  gamma: 0.0
  train_batch_size: 128
  sgd_minibatch_size: 32 # Default is 128
  num_sgd_iter: 8 # Default is 30
  lambda_: 0.95
  kl_target: 0.01
  kl_coeff: 0.2
  use_kl_loss: True
  clip_param: 0.2
  grad_clip: 0.5

model:

  feature_model:
    n_embd: 128
    n_head: 4
    bias: False
    dropout: 0.0
    layers: 3

  satellite_model:
    n_embd: 512
    n_head: 4
    bias: False
    dropout: 0.0
    layers: 3


env:
  sim_rate: 1.0
  max_step_duration: 200.0
  time_limit: 11400 # about 2 orbits
  n_access_windows: &n_access_windows 10
  n_sats: 10

  n_trajectory_factor: 20

  min_tasks: 500
  max_tasks: 500

  max_sat_coordination: &max_sat_coordination 3

  observation_keys: ['x', 'y', 'z', 'window_index', 'window_index_offset', 'priority', 'n_required_collects']
  observation_defaults:
    x: 0
    y: 0
    z: 0
    window_index: 100
    window_index_offset: 100
    priority: -1
    n_required_collects: 0
  observation_normalization_terms:
    x: 1
    y: 1
    z: 1
    window_index: 100
    window_index_offset: 100
    priority: 1
    n_required_collects: *max_sat_coordination

