
local_mode: false
use_gpu: true
resume: false
checkpoint_path: "/data/nm/v153_geo/checkpoint_300/"  # Set this to the checkpoint path when resuming

env_runners:
  sample_timeout_s: 1000000.0
  num_env_runners: 47
  num_cpus_per_env_runner: 1

training:
  steps: 100000

training_args:
  lr: 0.00003
  gamma: 0.98
  train_batch_size: 300
  minibatch_size: 64 # Default is 128
  num_sgd_iter: 16 # Default is 30
  lambda_: 0.95
  kl_target: 0.01
  kl_coeff: 0.2
  use_kl_loss: True
  clip_param: 0.2
  grad_clip: 0.5
  # lr: 0.00003
  # gamma: 0.99
  # train_batch_size: 512
  # sgd_minibatch_size: 32 # Default is 128
  # num_sgd_iter: 256 # Default is 30
  # lambda_: 0.95
  # kl_target: 0.01
  # kl_coeff: 0.2
  # use_kl_loss: True
  # clip_param: 0.2
  # grad_clip: 0.5
  # entropy_coeff_schedule: [[0, 0.02], [100000, 0.01], [200000, 0.005]]

model:

  # resume_args:
  #   resume: True
  #   checkpoint_path: "/data/nm/v135_geo/PPO_2024-11-21_15-06-33/PPO_SatelliteTasking_de70a_00000_0_2024-11-21_15-06-33/checkpoint_000198/policies/default_policy/model/model.pt"

  feature_model:
    n_embd: 128
    n_head: 4
    bias: False
    dropout: 0.0
    layers: 3

  satellite_model:
    task_embd: 128
    n_embd: 1024
    n_head: 4
    bias: False
    dropout: 0.0
    layers: 3


env:
  sim_rate: 1.0
  max_step_duration: &max_step_duration 200.0
  time_limit: 3000 # 15 steps #21400 #11400 # about 2 orbits
  n_access_windows: &n_access_windows 20
  n_sats: 10

  n_trajectory_factor: 20

  min_tasks: 100
  max_tasks: 100

  max_sat_coordination: &max_sat_coordination 2
  task_min_storage_size: 100
  task_max_storage_size: &task_max_storage_size 1000
  task_min_duration: 1
  task_max_duration: 30
  task_min_elev: 0.7853981633974483 # 45 degrees in radians

  # Empty task
  noop_task_priority: 0.0 # Priority and rewards are correlated
  downlink_task_priority: 0.0
  charge_task_priority: 0.0
  desat_task_priority: 0.0

  observation_keys: 
      # Task location features (required for geospatial coordination)
      # - Latitude/longitude are encoded as sin/cos pairs for circular continuity
      # - These features uniquely identify each task location
      # - Multiple satellites can coordinate collection of the same geospatial task
    - 'task_lat_sin'
    - 'task_lat_cos'
    - 'task_lon_sin'
    - 'task_lon_cos'
    # This feature lets the NN know how many sats to coordinate on the same task
    - 'simultaneous_collects_required'
    # This feature lets the NN plan ahead for power and storage
    - 'window_index_offset'
    - 'priority'
    - 'is_data_downlink'
    - 'is_charge_task'
    - 'is_desat_task'
    - 'wheel_speed_1'
    - 'wheel_speed_2'
    - 'wheel_speed_3'
    - 'power_percentage'
    - 'storage_percentage'
    - 'in_eclipse'
  observation_defaults:
    task_lat_sin: 0
    task_lat_cos: 0
    task_lon_sin: 0
    task_lon_cos: 0
    window_index_offset: 20
    priority: -1
    simultaneous_collects_required: 0
    is_data_downlink: 0
    task_storage_size: 0
    is_charge_task: 0
    in_eclipse: 0
    is_desat_task: 0
    wheel_speed_1: 0
    wheel_speed_2: 0
    wheel_speed_3: 0
    power_percentage: 0
    storage_percentage: 0

  observation_normalization_terms:
    task_lat_sin: 1
    task_lat_cos: 1
    task_lon_sin: 1
    task_lon_cos: 1
    window_index_offset: *n_access_windows
    priority: 1
    simultaneous_collects_required: *max_sat_coordination
    is_data_downlink: 1
    task_storage_size: *task_max_storage_size
    is_charge_task: 1
    in_eclipse: 1
    is_desat_task: 1
    wheel_speed_1: 1.2
    wheel_speed_2: 1.2
    wheel_speed_3: 1.2
    power_percentage: 1
    storage_percentage: 1

  groundStations:
    - name: Boulder
      lat: 40.009971
      long: -105.243895
      elev: 1624
    - name: Merritt
      lat: 28.3181
      long: -80.666
      elev: 0.9144
    - name: Singapore
      lat: 1.3521
      long: 103.8198
      elev: 15
    - name: Weilheim
      lat: 47.8407
      long: 11.1421
      elev: 563
    - name: Santiago
      lat: -33.4489
      long: -70.6693
      elev: 570
    - name: Dongara
      lat: -29.2452
      long: 114.9326
      elev: 34
    - name: Hawaii
      lat: 19.8968
      long: -155.5828
      elev: 9


